version: '3'
services:
# The first node and config in the first datacenter.
    node1:
        image: cassandra:4.1.1
        container_name: Cass_node1
        hostname: node1
        # use static ip address
        networks:
            netring:
              ipv4_address: 172.16.0.2
        # Docker container environment variable. We are using the
        # CASSANDRA_CLUSTER_NAME to name the cluster. This needs to be the same
        # across clusters. We are also declaring that node1 is a seed node etc.
        environment:
            - DS_LICENSE=accept
            - SEEDS=node1
            - START_RPC=false
            - CLUSTER_NAME=Cass_cluster
            - NUM_TOKENS=3
            - DC=DC1
            - RACK=RAC1
            - MAX_HEAP_SIZE=1000000000
        # Exposing ports for inter cluster communication
        expose:
            # Intra-node communication
            - 7000
            # TLS intra-node communication
            - 7001
            # JMX
            - 7199
            # CQL
            - 9042
            # CQL SSL
            - 9142
        ports:
            - 7000:7000
            - 9042:9042
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
    node2:
        image: cassandra:4.1.1
        container_name: Cass_node2
        hostname: node2
        networks:
            netring:
              ipv4_address: 172.16.0.3
        environment:
            - DS_LICENSE=accept
            - SEEDS=node1
            - START_RPC=false
            - CLUSTER_NAME=Cass_cluster
            - NUM_TOKENS=3
            - DC=DC2
            - RACK=RAC1
            - MAX_HEAP_SIZE=1000000000
        expose:
            - 7000
            - 7001
            - 7199
            - 9042
            - 9142
        ports:
            - 7000:7000
            - 9043:9042
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
        depends_on:
            - node1
    node3:
        image: cassandra:4.1.1
        container_name: Cass_node3
        hostname: node3
        networks:
          netring:
              ipv4_address: 172.16.0.4
        environment:
            - DS_LICENSE=accept
            - SEEDS=node1
            - START_RPC=false
            - CLUSTER_NAME=Cass_cluster
            - NUM_TOKENS=3
            - DC=DC1
            - RACK=RAC1
            - MAX_HEAP_SIZE=1000000000
        expose:
            - 7000
            - 7001
            - 7199
            - 9042
            - 9142
        ports:
            - 7000:7000
            - 9044:9042
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
        depends_on:
            - node1
networks:
    netring:
      driver: bridge
      attachable: true
      ipam:
          config:
              - subnet: 172.16.0.0/16
